# - A. Tomiya 2025/01/11

# Current reference defaults. These preserve the existing behavior unless a
# caller supplies explicit arguments.
const CURRENT_LOG_EPSILON = 1e-7
const CURRENT_LEVEL_STD_MULTIPLIER = 1.2
const CURRENT_LEVEL_STEP = 0.05
const LEVEL_TARGET_LEGACY_NEGLOG_HIGH = :legacy_neglog_high
const LEVEL_TARGET_RAW_HIGH = :raw_high
const LEVEL_TARGET_ACTION_DENSITY_HIGH = :action_density_high
const CURRENT_LEVEL_TARGET = LEVEL_TARGET_ACTION_DENSITY_HIGH
const CURRENT_RAW_HIGH_QUANTILES = (0.90, 0.95, 0.98, 0.99)

const CURRENT_MOVIE_FRAMERATE = 12
const CURRENT_MOVIE_NLOOPS = 1
const CURRENT_FIGURE_SIZE = (800, 800)
const CURRENT_CACHE_RENDER_SLICES = true
const CURRENT_SHOW_RENDER_PROGRESS = true
const CURRENT_RENDER_PROGRESS_DESCRIPTION = "Rendering frames..."
const CURRENT_RENDER_PROGRESS_SHOWSPEED = true
const CAMERA_MOTION_STATIC = :static
const CAMERA_MOTION_ORBIT = :orbit
const CURRENT_CAMERA_MOTION = CAMERA_MOTION_STATIC
const CURRENT_CAMERA_AZIMUTH = -0.62pi
const CURRENT_CAMERA_ELEVATION = 0.18pi
const CURRENT_CAMERA_MESH_PERSPECTIVENESS = 0.58
const CURRENT_CAMERA_ORBIT_TURNS = 1.0
const CURRENT_CAMERA_ORBIT_FRAMERATE = 14
const CURRENT_CAMERA_ORBIT_SECONDS = 640 / CURRENT_CAMERA_ORBIT_FRAMERATE
const CURRENT_CAMERA_ORBIT_PERSPECTIVENESS = 0.0
const CURRENT_CAMERA_ORBIT_VIEWMODE = :fit
const FRAME_MODE_SEQUENCE = :slice4_sequence
const FRAME_MODE_FIXED = :fixed_slice4
const CURRENT_FRAME_MODE = FRAME_MODE_SEQUENCE
const CURRENT_FIXED_SLICE4 = 1
const CURRENT_COLORMAP = :viridis
const CURRENT_ALPHA = 1.0
const CURRENT_TRANSPARENCY = false
const CURRENT_RAW_HIGH_COLOR_QUANTILES = (0.90, 0.995)
const CURRENT_RAW_HIGH_ALPHA = 0.45
const CURRENT_RAW_HIGH_TRANSPARENCY = true
const RENDER_STYLE_CURRENT = :current
const RENDER_STYLE_PLAQUETTE_THERMAL = :plaquette_thermal
const RENDER_STYLE_ACTION_DENSITY_BLOB = :action_density_blob
const CURRENT_RENDER_STYLE = RENDER_STYLE_ACTION_DENSITY_BLOB
const CURRENT_PLAQUETTE_THERMAL_LEVEL_QUANTILES = (0.85, 0.90, 0.95, 0.98)
const CURRENT_PLAQUETTE_THERMAL_COLOR_QUANTILES = (0.85, 0.995)
const CURRENT_PLAQUETTE_THERMAL_COLORMAP = (:cyan, :turquoise, :yellow, :red)
const CURRENT_PLAQUETTE_THERMAL_ALPHA = 0.65
const CURRENT_PLAQUETTE_THERMAL_TRANSPARENCY = true
const CURRENT_ACTION_DENSITY_SMOOTH_WEIGHT = 0.92
const CURRENT_ACTION_DENSITY_SMOOTH_PASSES = 1
const CURRENT_ACTION_DENSITY_BODY_QUANTILE = 0.84
const CURRENT_ACTION_DENSITY_UPSAMPLE_FACTOR = 4
const CURRENT_ACTION_DENSITY_POST_SMOOTH_WEIGHT = 0.88
const CURRENT_ACTION_DENSITY_POST_SMOOTH_PASSES = 1
const CURRENT_ACTION_DENSITY_TAUBIN_ITERATIONS = 42
const CURRENT_ACTION_DENSITY_TAUBIN_LAMBDA = 0.38
const CURRENT_ACTION_DENSITY_TAUBIN_MU = -0.40
const CURRENT_ACTION_DENSITY_TAUBIN_PIN_DOMAIN = false
const CURRENT_ACTION_DENSITY_COLOR_QUANTILES = (0.80, 0.999)
const CURRENT_ACTION_DENSITY_COLOR_RADIUS = 7
const CURRENT_ACTION_DENSITY_COLOR_TOP_FRACTION = 0.14
const CURRENT_ACTION_DENSITY_COLOR_STAT = :topmean
const CURRENT_ACTION_DENSITY_COLOR_PALETTE = :classic_thermo
const CURRENT_ACTION_DENSITY_COLOR_GAMMA = 1.0
const RENDER_THEME_LIGHT = :light
const RENDER_THEME_DARK = :dark
const CURRENT_RENDER_THEME = RENDER_THEME_LIGHT
const CURRENT_ASPECT = (1, 1, 1)
const CURRENT_TICK_DIGITS = 2
const CURRENT_TICK_STRIDE = 2
const DEFAULT_MOVIE_TITLE = "Plaquette log iso-surface"
const RAW_HIGH_MOVIE_TITLE = "Plaquette raw-deviation iso-surface"
const ACTION_DENSITY_BLOB_MOVIE_TITLE = "Action-density blob"

const CURRENT_BETA_ANIMATION_DEFAULT = 6.1
const CURRENT_FILENAME_DEFAULT = "conf_00000100.ildg"
const CURRENT_FLOW_STEPS_ANIMATION_DEFAULT = 200
const CURRENT_NWING = 0
const CURRENT_R0_FM = 0.48
const CURRENT_BETA_RANGE = (5.7, 6.57)
const CURRENT_LN_A_COEFFS = (-1.6805, -1.7139, 0.8155, -0.6667)
const CURRENT_LTOSEC = 10 / 3

const CURRENT_WILSONLINE_LOOP = [(1, +1), (2, +1), (1, -1), (2, -1)]
const CURRENT_WILSONLINE_TEMP_COUNT = 10
const CURRENT_PLAQUETTE_PLANES_4D = ((1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4))

const CURRENT_HEATBATH_DIM = 4
const CURRENT_HEATBATH_ITERATION_MAX = 100_000
const CURRENT_HEATBATH_SWEEPS = 20
const CURRENT_HEATBATH_REPORT_INTERVAL = 5
const CURRENT_GENERATION_INITIAL_CONDITION = "cold"
const CURRENT_PLAQUETTE_PLANE_COUNT_4D = 6

const CURRENT_README_LATTICE = (24, 24, 24, 32)
const CURRENT_README_BETA = 6.0
const CURRENT_README_NC = 3
const CURRENT_README_FLOW_STEPS = 200

const CURRENT_TEST_LATTICE = (12, 12, 12, 16)
const CURRENT_TEST_BETA = 6.0
const CURRENT_TEST_NC = 3
const CURRENT_TEST_FLOW_STEPS = 10
